### PR TITLE
setuptools

### PR DESCRIPTION
**Pull request by hannorein**
Have a look at this. This solution is somewhat different from the generator trick but it works for me. 

I did not find an easy way for the `runtime_library_dirs` and `extra_link_args`. I don't know when they are needed (linux?). 

This also only works for setuptools, e.g. not distutils. Not sure what to do there? Maybe just require setuptools in the package?

### CODE REVIEW

**Comment by hannorein** [comment]
(clearly something is not working yet)

**Comment by dtamayo** [comment]
Hm, I have to head home now, but I tried it and (I guess like you found) there’s no attribute runtime_library_dirs or extra_link_args.

The former only works on linux and it sets the rpath for you automatically.  The latter is what I had to do if we’re in OS X to set the rpath.  Without them it will install, but when you try to load libreboundx.so, it won’t be able to find librebound.so.

That looks very promising though, since the import rebound in the finalize options didn’t fail…I’ll try to look into it if I can

**Comment by hannorein** [comment]
The latest commit seems to fix everything for. It works on travis, linux and macosx. On macosx I tested both python 2.7 and 3.4. 

Tested with the following commands:
    
```bash
    mkdir newer
    virtualenv venv
    source venv/bin/activate
    pip install git+https://github.com/hannorein/reboundx.git
    wget https://gist.githubusercontent.com/hannorein/9d0f7a1b64e0a2fce5fb/raw/a1ec5add13b5fe0e71c0557eec00a46f8b949a29/Migration.py
    python Migration.py
```

**Comment by dtamayo** [comment]
Seem to work great!  I tested on CentOS python 2.7 and 3.4 and my mac.  I added some error messages in case it fails at different points, asking people to contact me if they get the error.  That might be the fastest way to find any problems.  I'm also giving the planetary discussion on Friday on a reboundx demonstration, so that will be another good test.  Thanks again

**Pull request merged**
