### PR TITLE
Fixed GLFW errors on travis, works with new reb_transformation syntax

### PR DESCRIPTION
**Pull request by hannorein**
Don't merge this just yet. 

This should work once I've merged the changes from the whfasttp1 branch into the REBOUND master branch.

### CODE REVIEW

**Comment by hannorein** [comment]
Also fixes #52.

**Comment by dtamayo** [comment]
Thanks a lot!

**Comment by dfm** [comment]
:wave: I was just coming over here because I hit this same issue.

**Comment by hannorein** [comment]
I'll merge it shortly, just waiting for travis to finish the checks.

**Comment by hannorein** [comment]
@dtamayo, all tests passed. If you have time, maybe you can push it to pypi so that it works for people using pip install. Thanks!

**Pull request merged**
