### PR TITLE
Documentation Changes

### PR DESCRIPTION
**Pull request by tigerchenlu98**
Reflects paper being accepted & on arXiv!

Also changed the documentation names of some examples.

### CODE REVIEW

**Comment by dtamayo** [comment]
hi Tiger, this is great. I can edit setup.py to for the new name, but is (Eggledton 1998) the right reference for obliquity sculpting of Kepler multis?

**Comment by tigerchenlu98** [comment]
You're right - changed that to Millholland & Laughlin 2019. And Hut 1981 is the better reference for pseudo-synchronization - changed that too.

**Comment by tigerchenlu98** [comment]
@dtamayo the link to Lu et. al (2023) on the website is showing up weird. I can't figure out what's wrong with my formatting in tides_spin.c - when you have the chance could you take a look? Thanks!

**Comment by dtamayo** [comment]
fixed! might take a sec to refresh on readthedocs

**Pull request merged**
