### PR TITLE
Lense thirring

### PR DESCRIPTION
**Pull request by aryaakmal**
An implementation of the relativistic Lense-Thirring effect due to a massive rotating body.

### CODE REVIEW

**Comment by dtamayo** [comment]
Thanks Arya, this is great!!

We recently added support dynamically tracking spins in REBOUND/REBOUNDx. I'm not too familiar with the details here--is there a feedback torque on the spin at this same level of approximation? I can certainly imagine you don't care about this effect in many scenarios, but it might be useful to refactor the code in a way that at least makes it straightforward to add that capability later. 

I can help with that, but not until after the semester ends. Do you need this now as a dependency for another project, or is this independent / can wait a couple weeks?

**Comment by aryaakmal** [comment]
Hi Dan,

 I certainly don't need this immediately, and there is no rush at all. Matt
has a grant to implement an N-body ephemeris (I am not a part of it) but I
was looking for low-hanging fruit from the park er al. DE440 paper, and
this seemed like the most straightforward element, so I went ahead and
coded it up. Feel free to incorporate it in reboundx if you feel  be it may
be useful. I need to think a bit more into the feedback torque question to
give you a confident authoritative answer - I would guess it is the same
level of approximation. But Matt may have more input in the meantime.

All the best,

Arya

**Comment by aryaakmal** [comment]
Hi Dan-

 Having thought about this for a few days, I think I've reached a tentative
conclusion. Since this effect is closely analogous to a magnetic dipole
interaction, I don't think there would be an associated torque in the case
where the spins of the objects are aligned or (exacly) anti-aligned. I
believe the torque would be present if the spins are mis-aligned, although
this effect should be very small, unless the two objects are both very
massive and/or spinning very rapidly.

So, for the "relatively" (;-) mundane physics the ephemeris and S.S.
dynamics people are concerned with, this would not be important. However,
the effect would be significant for less prosaic objects and systems. I
need to delve more deeply into the GR to convince myself more fully, but I
do believe that there would be more significant relativistic effects of
lower order than this interaction. If you have any insights into this,
please let me know.

I think it would be very cool to try to incorporate higher order general
relativistic effects into reboundx, but this  obviously needs  to be
approached systematically, not in the simplistic ad hoc way I have
proceeded.

best
Arya

**Comment by hannorein** [comment]
The astropy units package seems great and the community seems to be using it a lot. But I wish it were a standalone package. I don't like how astropy is become the new IDL where nothing can be done without it. There seem [plenty of alternatives](https://socialcompare.com/en/comparison/python-units-quantities-packages) out there which do only unit conversions. I've heard good thing about [pint](https://github.com/hgrecco/pint). I'd rather make pint a dependency than astropy.

**Comment by aryaakmal** [comment]
Thank you for cleaning this up, Dan. To the best of my knowledge this
effect is not significant other than for the sun. At least, I haven't seen
any implementations beyond that, so I would guess that it is of such high
order that noone has bothered to consider it. If and when you and Hanno are
ok with it, please feel free to incorporate it as you see fit.

-A.

**Comment by dtamayo** [comment]
Great, thanks @aryaakmal! @hannorein, that's a good point. How about adding neither of them as dependencies, hard-coding all the values in the examples, and adding a Units.ipynb example that isn't tracked by the github workflow that gives a couple examples using both astropy and pint? I think as a new student trying to get up and running quickly I would find that quite helpful.

**Comment by dtamayo** [comment]
Also I guess we need to remove python 2.7 from the tests!

**Comment by hannorein** [comment]
That sounds good. We could still include it in a separate workflow. On Jun 19, 2023, at 7:09 PM, Dan Tamayo ***@***.***> wrote:﻿
Great, thanks @aryaakmal! @hannorein, that's a good point. How about adding neither of them as dependencies, hard-coding all the values in the examples, and adding a Units.ipynb example that isn't tracked by the github workflow that gives a couple examples using both astropy and pint? I think as a new student trying to get up and running quickly I would find that quite helpful.

**Pull request merged**
