### PR TITLE
Add hyperlinked implementation paper

### PR DESCRIPTION
**Pull request by sabaronett**

### CODE REVIEW

**Comment by dtamayo** [comment]
Thanks Stanley!

It looks like whole blocks of documentation were moved around, so the diff is quite large and it's hard to tell what changed. What are the changes?

**Review by sabaronett — COMMENTED** [review]
@dtamayo, this single-line change to `src/interpolation.c` is the only important one I made (i.e., added a hyperlink to our paper on ADS). However, `effects.rst` seems to have changed significantly after following the instructions at the end of [6.3.1. Add Your Effect to the Main Documentation Page!](https://reboundx.readthedocs.io/en/latest/add_effect.html#add-your-effect-to-the-main-documentation-page) to rebuild the HTML pages with Doxygen.

**Comment by dtamayo** [comment]
Hi Stanley,

Sorry for the slow reply. That's odd. I just tried adding your one-liner myself and rerunning the documentation, and I just get the one-line change in effects.rst. It may be that something in how the documentation is built is platform dependent. In any case, I just made the change myself (and thanked you in the commit!). Really appreciate your help. 

And so sorry for the awful shooting at UNLV...what a senseless and devastating tragedy..

**Comment by sabaronett** [comment]
Hi Dan,

No worries. Thank you for your condolences. Luckily, I was (and still am) in NYC for my CCA pre-doc at the time but received alerts in real-time as it was unfolding and throughout the rest of the day.

The difference in rebuilding the documentation _is_ interesting, and I also wonder if it's platform dependent. However, I don't see the update having taken effect on the [Implemented Effects page](https://reboundx.readthedocs.io/en/latest/effects.html#parameter-interpolation) (screenshot below), even though your commit was about 40 hours ago. Does `readthedocs` take more than 24 hours to rebuild?

image

**Comment by dtamayo** [comment]
Hey @sabaronett,

Yeah it looks like it just takes a while to update. Seems to be working now!

**Comment by sabaronett** [comment]
Hi @dtamayo,

Sorry to keep bothering you, but are you sure? I'm still seeing this [here](https://reboundx.readthedocs.io/en/latest/effects.html#interpolation) across multiple browsers and when InPrivate or Incognito:

image

**Comment by dtamayo** [comment]
That's weird...maybe it's a caching issue? If I click on your link I see the same thing, but if I scroll up to the side bar and click implemented effects and then click on tides_constant_time_lag I see it updated

**Comment by sabaronett** [comment]
Ah, you're looking at the wrong effect. This pull request is for (1.11.1.) **Parameter Interpolation**, not (1.6.2.) tides_constant_time_lag (TCTL). The latter has had the correct implementation paper link for a while, but I noticed our paper was missing for the former. Hope that helps clarify things.

**Comment by dtamayo** [comment]
Agh, thanks for your persistence! It turns out the readthedocs config file format I was using was deprecated, and the readthedocs builds were failing. I've fixed this now and it seems to work. Thanks so much for the catch!

**Comment by sabaronett** [comment]
Ah, that might explain all the seemingly random changes to `effects.rst` in my original commit when I attempted to rebuild on my machine. Great job figuring that out, and no problem! Thanks again for helping link our paper.

**Pull request closed without merging**
