### PR TITLE
API changes for REBOUND version 4

### PR DESCRIPTION
**Pull request by hannorein**
Staging changes for REBOUND Version 4.

### CODE REVIEW

**Comment by hannorein** [comment]
I do not know how to temporarily change CI so that it pull rebound from my version4 branch. Might not be worth doing if we can run the unit tests locally for this PR.

**Comment by dtamayo** [comment]
When you push changes to version4 in the rebound repo, the REBOUNDx CI is checking out that version installing locally and then installing REBOUNDx. But yeah, if it doesn't work locally, then it's the same issue on the CI end. When I try to reproduce what you get, I get the same error as the CI spits out, saying implicit declaration of reb_orbit_from_particle. Is that the same issue of not finding the rebound.h file?

**Comment by hannorein** [comment]
The python units tests are passing now on my local machine. I don't think we can get the CI working before merging at least one of the rebound or reboundx development branches into the main branch. Neither this CI runs triggered by this pull request nor those by pushing to rebound will use the correct combination of "version4" branches. It's either rebound/main and reboundx/version4 or vice versa. 

It would be great if you can also confirm that the unit tests are working on your end. I'll hold off with merging version 4 of rebound into the main branch until I get a green light from you. No rush!

**Comment by hannorein** [comment]
There were as predicted a few hiccups (some examples needed more changes, an issue with Vec3d). But now all tests are passing. Up to you if you want to merge it immediately (I would suggest as a squash commit), or wait a little longer to let things settle...

**Comment by dtamayo** [comment]
Thank you!! I'm leaving tomorrow to visit Cornell, so I think I will wait until I get back on Friday when I'll be better able to deal with things that come up

**Pull request merged**
